Srver:
  port: 8088
spring:
  mail.host: smtp.gmail.com
  mail.port: 587
  mail.username: sinevichblogstudymail@gmail.com
  mail.password: bpbxaazayufedrhv
  mail.properties.mail.smtp.auth: true
  mail.properties.mail.smtp.starttls.enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/blogengine
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false



blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005
  result: false
  captchaDeleteTimeMinutes : 120