spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogengine
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005